version: '3'

services:

  db:
    image: mysql:5.7
    command:
      --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./mysqldb/:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: 'books_db'
      MYSQL_ROOT_PASSWORD: 12345
