# Generated by Django 2.2.8 on 2019-12-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Nomresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sinif',
                'verbose_name_plural': 'Sinifler',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.TimeField(verbose_name='Saat')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.Class')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
            ],
            options={
                'verbose_name': 'Mekteb',
                'verbose_name_plural': 'Mektebler',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Adi')),
                ('last_name', models.CharField(max_length=20, verbose_name='Soyadi')),
                ('position', models.CharField(choices=[('m', 'Muellim'), ('z', 'Muavin'), ('d', 'Direktor')], max_length=1, verbose_name='Vezifesi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schools', models.ManyToManyField(to='book_app.School')),
            ],
            options={
                'verbose_name': 'Shexs',
                'verbose_name_plural': 'Shexsler',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Ad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rel', models.ManyToManyField(through='book_app.Relation', to='book_app.Staff')),
            ],
            options={
                'verbose_name': 'Fenn',
                'verbose_name_plural': 'Fennler',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Adi')),
                ('last_name', models.CharField(max_length=20, verbose_name='Soyadi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='book_app.Class')),
            ],
            options={
                'verbose_name': 'Sagird',
                'verbose_name_plural': 'Sagirdler',
                'ordering': ('first_name',),
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.Staff'),
        ),
        migrations.AddField(
            model_name='relation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.Subject'),
        ),
    ]
